app:
  scheduler:
    enable: true
    interval: 10000
    update: 90000
    force-check-delay: 10000

github-client:
  base-url: https://api.github.com/

stackoverflow-client:
  base-url: https://api.stackexchange.com/2.3/

spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/scrapper
    password: postgres
    username: postgres
  liquibase:
    enabled: false

bot-client:
  base-url: http://localhost:8090/bot/api/v1/

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /scrapper/api/v1/swagger-ui

