app:
  telegram-token: ${TELEGRAM_API_KEY}
  kafka-producer-settings:
    bootstrap-servers: localhost:9092
    client-id: dlqGroup
    delivery-timeout: 100000
    linger-ms: 2000
    batch-size: 200000
    enable-idempotence: true
  kafka-consumer-settings:
    bootstrap-servers: localhost:9092
    group-id: consumerGroup
    auto-offset-reset: latest
    enable-auto-commit: true
    concurrency: 3
  kafka-update-topic:
    name: linkUpdate
    partitions: 1
    replicas: 1
  micrometer: messages-counter

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: info, health, prometheus
  server:
    port: 8091

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

scrapper-client:
  base-url: http://localhost:8080/scrapper/api/v1/

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  show-actuator: true
  swagger-ui:
    path: /bot/api/v1/swagger-ui
