/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.LinkToChatRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class LinkToChat extends TableImpl<LinkToChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINK_TO_CHAT</code>
     */
    public static final LinkToChat LINK_TO_CHAT = new LinkToChat();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinkToChatRecord> getRecordType() {
        return LinkToChatRecord.class;
    }

    /**
     * The column <code>LINK_TO_CHAT.CHAT_ID</code>.
     */
    public final TableField<LinkToChatRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINK_TO_CHAT.LINK_ID</code>.
     */
    public final TableField<LinkToChatRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private LinkToChat(Name alias, Table<LinkToChatRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinkToChat(Name alias, Table<LinkToChatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINK_TO_CHAT</code> table reference
     */
    public LinkToChat(String alias) {
        this(DSL.name(alias), LINK_TO_CHAT);
    }

    /**
     * Create an aliased <code>LINK_TO_CHAT</code> table reference
     */
    public LinkToChat(Name alias) {
        this(alias, LINK_TO_CHAT);
    }

    /**
     * Create a <code>LINK_TO_CHAT</code> table reference
     */
    public LinkToChat() {
        this(DSL.name("LINK_TO_CHAT"), null);
    }

    public <O extends Record> LinkToChat(Table<O> child, ForeignKey<O, LinkToChatRecord> key) {
        super(child, key, LINK_TO_CHAT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<LinkToChatRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_10A5;
    }

    @Override
    @NotNull
    public List<ForeignKey<LinkToChatRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_10, Keys.CONSTRAINT_10A);
    }

    private transient Chat _chat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null) {
            _chat = new Chat(this, Keys.CONSTRAINT_10);
        }

        return _chat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null) {
            _link = new Link(this, Keys.CONSTRAINT_10A);
        }

        return _link;
    }

    @Override
    @NotNull
    public LinkToChat as(String alias) {
        return new LinkToChat(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinkToChat as(Name alias) {
        return new LinkToChat(alias, this);
    }

    @Override
    @NotNull
    public LinkToChat as(Table<?> alias) {
        return new LinkToChat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkToChat rename(String name) {
        return new LinkToChat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkToChat rename(Name name) {
        return new LinkToChat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkToChat rename(Table<?> name) {
        return new LinkToChat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
