/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubRepos implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private Long stars;
    private Long issues;

    public GithubRepos() {
    }

    public GithubRepos(GithubRepos value) {
        this.linkId = value.linkId;
        this.stars = value.stars;
        this.issues = value.issues;
    }

    @ConstructorProperties({"linkId", "stars", "issues"})
    public GithubRepos(
        @NotNull Long linkId,
        @NotNull Long stars,
        @NotNull Long issues
    ) {
        this.linkId = linkId;
        this.stars = stars;
        this.issues = issues;
    }

    /**
     * Getter for <code>GITHUB_REPOS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>GITHUB_REPOS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>GITHUB_REPOS.STARS</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getStars() {
        return this.stars;
    }

    /**
     * Setter for <code>GITHUB_REPOS.STARS</code>.
     */
    public void setStars(@NotNull Long stars) {
        this.stars = stars;
    }

    /**
     * Getter for <code>GITHUB_REPOS.ISSUES</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getIssues() {
        return this.issues;
    }

    /**
     * Setter for <code>GITHUB_REPOS.ISSUES</code>.
     */
    public void setIssues(@NotNull Long issues) {
        this.issues = issues;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GithubRepos other = (GithubRepos) obj;
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.stars == null) {
            if (other.stars != null) {
                return false;
            }
        } else if (!this.stars.equals(other.stars)) {
            return false;
        }
        if (this.issues == null) {
            if (other.issues != null) {
                return false;
            }
        } else if (!this.issues.equals(other.issues)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.stars == null) ? 0 : this.stars.hashCode());
        result = prime * result + ((this.issues == null) ? 0 : this.issues.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubRepos (");

        sb.append(linkId);
        sb.append(", ").append(stars);
        sb.append(", ").append(issues);

        sb.append(")");
        return sb.toString();
    }
}
