/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.GithubRepos;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.LinkToChat;
import edu.java.domain.jooq.tables.records.ChatRecord;
import edu.java.domain.jooq.tables.records.GithubReposRecord;
import edu.java.domain.jooq.tables.records.LinkRecord;
import edu.java.domain.jooq.tables.records.LinkToChatRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_1F =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1F"), new TableField[] {Chat.CHAT.ID}, true);
    public static final UniqueKey<GithubReposRecord> CONSTRAINT_3A = Internal.createUniqueKey(GithubRepos.GITHUB_REPOS,
        DSL.name("CONSTRAINT_3A"),
        new TableField[] {GithubRepos.GITHUB_REPOS.LINK_ID},
        true
    );
    public static final UniqueKey<GithubReposRecord> CONSTRAINT_3AB = Internal.createUniqueKey(GithubRepos.GITHUB_REPOS,
        DSL.name("CONSTRAINT_3AB"),
        new TableField[] {GithubRepos.GITHUB_REPOS.LINK_ID},
        true
    );
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URL}, true);
    public static final UniqueKey<LinkToChatRecord> CONSTRAINT_10A5 = Internal.createUniqueKey(LinkToChat.LINK_TO_CHAT,
        DSL.name("CONSTRAINT_10A5"),
        new TableField[] {LinkToChat.LINK_TO_CHAT.CHAT_ID, LinkToChat.LINK_TO_CHAT.LINK_ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GithubReposRecord, LinkRecord> CONSTRAINT_3 =
        Internal.createForeignKey(GithubRepos.GITHUB_REPOS,
            DSL.name("CONSTRAINT_3"),
            new TableField[] {GithubRepos.GITHUB_REPOS.LINK_ID},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.ID},
            true
        );
    public static final ForeignKey<LinkToChatRecord, ChatRecord> CONSTRAINT_10 =
        Internal.createForeignKey(LinkToChat.LINK_TO_CHAT,
            DSL.name("CONSTRAINT_10"),
            new TableField[] {LinkToChat.LINK_TO_CHAT.CHAT_ID},
            Keys.CONSTRAINT_1,
            new TableField[] {Chat.CHAT.ID},
            true
        );
    public static final ForeignKey<LinkToChatRecord, LinkRecord> CONSTRAINT_10A =
        Internal.createForeignKey(LinkToChat.LINK_TO_CHAT,
            DSL.name("CONSTRAINT_10A"),
            new TableField[] {LinkToChat.LINK_TO_CHAT.LINK_ID},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.ID},
            true
        );
}
